#include "ColorRandomizer.h"
#include <QColor>

//Copied from QColor.cpp in order to random only specific SVG Colors
static const struct SVGData {
    const char *name;
} svgTbl[] = {
    { "aliceblue" },
    { "antiquewhite" },
    { "aqua" },
    { "aquamarine" },
    { "azure" },
    { "beige" },
    { "bisque" },
    { "black" },
    { "blanchedalmond" },
    { "blue" },
    { "blueviolet" },
    { "brown" },
    { "burlywood" },
    { "cadetblue" },
    { "chartreuse" },
    { "chocolate" },
    { "coral" },
    { "cornflowerblue" },
    { "cornsilk" },
    { "crimson" },
    { "cyan" },
    { "darkblue" },
    { "darkcyan" },
    { "darkgoldenrod" },
    { "darkgray" },
    { "darkgreen" },
    { "darkgrey" },
    { "darkkhaki" },
    { "darkmagenta" },
    { "darkolivegreen" },
    { "darkorange" },
    { "darkorchid" },
    { "darkred" },
    { "darksalmon" },
    { "darkseagreen" },
    { "darkslateblue" },
    { "darkslategray" },
    { "darkslategrey" },
    { "darkturquoise" },
    { "darkviolet" },
    { "deeppink" },
    { "deepskyblue" },
    { "dimgray" },
    { "dimgrey" },
    { "dodgerblue" },
    { "firebrick" },
    { "floralwhite" },
    { "forestgreen" },
    { "fuchsia" },
    { "gainsboro" },
    { "ghostwhite" },
    { "gold" },
    { "goldenrod" },
    { "gray" },
    { "green" },
    { "greenyellow" },
    { "grey" },
    { "honeydew" },
    { "hotpink" },
    { "indianred" },
    { "indigo" },
    { "ivory" },
    { "khaki" },
    { "lavender" },
    { "lavenderblush" },
    { "lawngreen" },
    { "lemonchiffon" },
    { "lightblue" },
    { "lightcoral" },
    { "lightcyan" },
    { "lightgoldenrodyellow" },
    { "lightgray" },
    { "lightgreen" },
    { "lightgrey" },
    { "lightpink" },
    { "lightsalmon" },
    { "lightseagreen" },
    { "lightskyblue" },
    { "lightslategray" },
    { "lightslategrey" },
    { "lightsteelblue" },
    { "lightyellow" },
    { "lime" },
    { "limegreen" },
    { "linen" },
    { "magenta" },
    { "maroon" },
    { "mediumaquamarine" },
    { "mediumblue" },
    { "mediumorchid" },
    { "mediumpurple" },
    { "mediumseagreen" },
    { "mediumslateblue" },
    { "mediumspringgreen" },
    { "mediumturquoise" },
    { "mediumvioletred" },
    { "midnightblue" },
    { "mintcream" },
    { "mistyrose" },
    { "moccasin" },
    { "navajowhite" },
    { "navy" },
    { "oldlace" },
    { "olive" },
    { "olivedrab" },
    { "orange" },
    { "orangered" },
    { "orchid" },
    { "palegoldenrod" },
    { "palegreen" },
    { "paleturquoise" },
    { "palevioletred" },
    { "papayawhip" },
    { "peachpuff" },
    { "peru" },
    { "pink" },
    { "plum" },
    { "powderblue" },
    { "purple" },
    { "red" },
    { "rosybrown" },
    { "royalblue" },
    { "saddlebrown" },
    { "salmon" },
    { "sandybrown" },
    { "seagreen" },
    { "seashell" },
    { "sienna" },
    { "silver" },
    { "skyblue" },
    { "slateblue" },
    { "slategray" },
    { "slategrey" },
    { "snow" },
    { "springgreen" },
    { "steelblue" },
    { "tan" },
    { "teal" },
    { "thistle" },
    { "tomato" },
    { "transparent" },
    { "turquoise" },
    { "violet" },
    { "wheat" },
    { "white" },
    { "whitesmoke" },
    { "yellow" },
    { "yellowgreen" }
};

static const int svgTblSize = 148;

QString ColorRandomizer::randomColor()
{
   int randSVG = qrand() % svgTblSize;

   return QString(svgTbl[randSVG].name);
}

qreal ColorRandomizer::colorLightness(QString baseColor)
{
    QColor baseQColor;
    baseQColor.setNamedColor(baseColor);
    return baseQColor.lightnessF();
}
